# Config
baseUrl: "/Yamblg/"
userUrl: "https://l3anav.github.io"
email: "leandroav.dev@gmail.com"
siteTitle: "Yamblg | Crea tu blog r√°pidamente"
useSectionPost:
    active: true
    limitOfPost: 5
usePinned:
    active: true
    