# Config
userUrl: "https://l3anav.github.io"
baseUrl: "/Yamblg"
email: "leandroav.dev@gmail.com"
siteTitle: "Yamblg | Crea tu blog r√°pidamente"
useSectionPost:
    active: true
    limitOfPost: 5
    method: "Latest"
usePinned:
    active: true
    